In [1]:
import os

path = os.getcwd()
# find the string 'project' in the path, return index
index_project = path.find('project')
# slice the path from the index of 'project' to the end
project_path = path[:index_project+7]
# set the working directory
os.chdir(project_path)
print(f'Project path set to: {os.getcwd()}')

Project path set to: c:\Github\ode-biomarker-project

In [2]:
from PathLoader import PathLoader
path_loader = PathLoader('data_config.env', 'current_user.env')

In [3]:
from DataLink import DataLink
data_link = DataLink(path_loader, 'data_codes.csv')

## Loading FGFR4 Drug Response Datasets from DataLink

In [4]:
# load in original ccle data
loading_code = 'generic-gdsc-1-FGFR_0939-LN_IC50-fgfr4_ccle_dynamic_features-true-Row'
# generic-gdsc-{number}-{drug_name}-{target_label}-{dataset_name}-{replace_index}-{row_index}
feature_data, label_data = data_link.get_data_using_code(loading_code)

In [5]:
feature_data.head()

,pIGFR_auc,pIGFR_median,pIGFR_tfc,pIGFR_tmax,pIGFR_max,pIGFR_tmin,pIGFR_min,pIGFR_ttsv,pIGFR_tsv,pIGFR_init,...,amTORC2_auc,amTORC2_median,amTORC2_tfc,amTORC2_tmax,amTORC2_max,amTORC2_tmin,amTORC2_min,amTORC2_ttsv,amTORC2_tsv,amTORC2_init
SIDM01085,0.019410,0.021032,4.682872,1.0,0.032885,0.04,0.005787,0.04,0.005787,0.005787,...,0.001717,0.001599,5.486629,1,0.003834,0.04,0.000591,0.04,0.000591,0.000591
SIDM00949,0.077292,0.084704,9.089875,1.0,0.140803,0.04,0.013955,0.04,0.013955,0.013955,...,0.218305,0.226915,0.364546,1,0.264206,0.04,0.193622,0.04,0.193622,0.193622
SIDM00494,0.010086,0.011210,3.560627,1.0,0.015136,0.04,0.003319,0.04,0.003319,0.003319,...,0.019850,0.020458,0.403167,1,0.024825,0.04,0.017692,0.04,0.017692,0.017692
SIDM00377,0.036978,0.039602,5.138051,1.0,0.065341,0.04,0.010645,0.04,0.010645,0.010645,...,0.000361,0.000332,1.189183,1,0.000639,0.04,0.000292,0.04,0.000292,0.000292
SIDM00988,0.027368,0.030932,8.449997,1.0,0.039991,0.04,0.004232,0.04,0.004232,0.004232,...,0.008990,0.009058,0.465354,1,0.011839,0.12,0.008078,0.04,0.008079,0.008079

## Loading FGFR4 Dynamic Features

In [5]:
data_link.load_data_code('fgfr4_ccle_dynamic_features')
fgfr4_dyn_features = data_link.data_code_database['fgfr4_ccle_dynamic_features']
fgfr4_dyn_features.set_index('Row', inplace=True)

In [6]:
fgfr4_dyn_features.head()

,pIGFR_auc,pIGFR_median,pIGFR_tfc,pIGFR_tmax,pIGFR_max,pIGFR_tmin,pIGFR_min,pIGFR_ttsv,pIGFR_tsv,pIGFR_init,...,amTORC2_auc,amTORC2_median,amTORC2_tfc,amTORC2_tmax,amTORC2_max,amTORC2_tmin,amTORC2_min,amTORC2_ttsv,amTORC2_tsv,amTORC2_init
Row,,,,,,,,,,,,,,,,,,,,,
ACH-001113,0.019879,0.022585,5.339313,1.0,0.029060,0.04,0.004584,0.04,0.004584,0.004584,...,0.038656,0.039956,0.334899,1,0.047065,0.08,0.035257,0.04,0.035257,0.035257
ACH-001289,0.047131,0.051773,9.378872,1.0,0.083667,0.04,0.008061,0.04,0.008061,0.008061,...,0.000253,0.000261,0.144059,1,0.000289,0.04,0.000252,0.04,0.000252,0.000252
ACH-001339,0.107427,0.124875,11.832264,1.0,0.183883,0.04,0.014330,0.40,0.099500,0.014330,...,0.756770,0.788399,0.280706,1,0.885227,0.04,0.691203,0.04,0.691203,0.691203
ACH-001538,0.018977,0.020471,6.192774,1.0,0.033563,0.04,0.004666,0.04,0.004666,0.004666,...,0.028552,0.029323,0.815663,1,0.039862,0.04,0.021955,0.04,0.021955,0.021955
ACH-000242,0.019410,0.021032,4.682872,1.0,0.032885,0.04,0.005787,0.04,0.005787,0.005787,...,0.001717,0.001599,5.486629,1,0.003834,0.04,0.000591,0.04,0.000591,0.000591

In [8]:
data_link.load_data_code('ccle_sample_info')
ccle_sample_info = data_link.data_code_database['ccle_sample_info']

In [9]:
ccle_sample_info.head() # Sanger_Model_ID

,DepMap_ID,cell_line_name,stripped_cell_line_name,CCLE_Name,alias,COSMICID,sex,source,RRID,WTSI_Master_Cell_ID,...,lineage_sub_subtype,lineage_molecular_subtype,default_growth_pattern,model_manipulation,model_manipulation_details,patient_id,parent_depmap_id,Cellosaurus_NCIt_disease,Cellosaurus_NCIt_id,Cellosaurus_issues
0,ACH-000016,SLR 21,SLR21,SLR21_KIDNEY,NaN,NaN,NaN,Academic lab,CVCL_V607,NaN,...,NaN,NaN,NaN,NaN,NaN,PT-JnARLB,NaN,Clear cell renal cell carcinoma,C4033,NaN
1,ACH-000032,MHH-CALL-3,MHHCALL3,MHHCALL3_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,NaN,NaN,Female,DSMZ,CVCL_0089,NaN,...,b_cell,NaN,NaN,NaN,NaN,PT-p2KOyI,NaN,Childhood B acute lymphoblastic leukemia,C9140,NaN
2,ACH-000033,NCI-H1819,NCIH1819,NCIH1819_LUNG,NaN,NaN,Female,Academic lab,CVCL_1497,NaN,...,NSCLC_adenocarcinoma,NaN,NaN,NaN,NaN,PT-9p1WQv,NaN,Lung adenocarcinoma,C3512,NaN
3,ACH-000043,Hs 895.T,HS895T,HS895T_FIBROBLAST,NaN,NaN,Female,ATCC,CVCL_0993,NaN,...,NaN,NaN,2D: adherent,NaN,NaN,PT-rTUVZQ,NaN,Melanoma,C3224,NaN
4,ACH-000049,HEK TE,HEKTE,HEKTE_KIDNEY,NaN,NaN,NaN,Academic lab,CVCL_WS59,NaN,...,NaN,NaN,NaN,immortalized,NaN,PT-qWYYgr,NaN,NaN,NaN,No information is available about this cell li...

In [21]:
import pandas as pd 

def dataset_to_sanger_model_id_from_ccle(df: pd.DataFrame, ccle_info_df: pd.DataFrame):
    '''
    Transforms DepMap_ID based-indices of the dataframe to Sanger_Model_ID
    input: df: pd.DataFrame, must have 'ACH-000000' formatted index as cell line identifiers 
    output: pd.DataFrame, with Sanger_Model_ID as index
    '''
    ccle_IDs = ccle_info_df[['DepMap_ID', 'Sanger_Model_ID']]
    ccle_IDs.set_index('DepMap_ID', inplace=True)

    transformed_df = df.join(ccle_IDs, how='inner')
    # remove rows with NaN for Sanger_Model_ID
    transformed_df.dropna(subset=['Sanger_Model_ID'], inplace=True)
    transformed_df.set_index('Sanger_Model_ID', inplace=True)
    return transformed_df

In [22]:
sanger_df = dataset_to_sanger_model_id_from_ccle(fgfr4_dyn_features, ccle_sample_info)

### CCLE mRNA Full Table

In [4]:
data_link.load_data_code('ccle')
ccle_df = data_link.data_code_database['ccle']

In [5]:
ccle_df.head()

,CELLLINE,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,...,H3C2,H3C3,AC098582.1,DUS4L-BCAP29,C8orf44-SGK3,ELOA3B,NPBWR1,ELOA3D,ELOA3,CDR1
0,ACH-001113,4.331992,0.000000,7.364397,2.792855,4.470537,0.028569,1.226509,3.042644,6.499686,...,2.689299,0.189034,0.201634,2.130931,0.555816,0.0,0.275007,0.0,0.0,0.000000
1,ACH-001289,4.566815,0.584963,7.106537,2.543496,3.504620,0.000000,0.189034,3.813525,4.221104,...,1.286881,1.049631,0.321928,1.464668,0.632268,0.0,0.014355,0.0,0.0,0.000000
2,ACH-001339,3.150560,0.000000,7.379032,2.333424,4.227279,0.056584,1.310340,6.687061,3.682573,...,0.594549,1.097611,0.831877,2.946731,0.475085,0.0,0.084064,0.0,0.0,0.042644
3,ACH-001538,5.085340,0.000000,7.154109,2.545968,3.084064,0.000000,5.868143,6.165309,4.489928,...,0.214125,0.632268,0.298658,1.641546,0.443607,0.0,0.028569,0.0,0.0,0.000000
4,ACH-000242,6.729145,0.000000,6.537607,2.456806,3.867896,0.799087,7.208381,5.569856,7.127014,...,1.117695,2.358959,0.084064,1.910733,0.000000,0.0,0.464668,0.0,0.0,0.000000

### Goncalves Proteomics Full Table

In [6]:
data_link.load_data_code('single_peptide_exclusion_matrix')
goncalves_df = data_link.data_code_database['single_peptide_exclusion_matrix']

In [7]:
goncalves_df.head()

,P37108;SRP14_HUMAN,Q96JP5;ZFP91_HUMAN,Q9Y4H2;IRS2_HUMAN,P36578;RL4_HUMAN,Q6SPF0;SAMD1_HUMAN,O76031;CLPX_HUMAN,Q8WUQ7;CATIN_HUMAN,A6NIH7;U119B_HUMAN,Q9BTD8;RBM42_HUMAN,Q9P258;RCC2_HUMAN,...,P33151;CADH5_HUMAN,Q5EBL4;RIPL1_HUMAN,P49715;CEBPA_HUMAN,Q5TA45;INT11_HUMAN,O14924;RGS12_HUMAN,Q7Z3B1;NEGR1_HUMAN,O60669;MOT2_HUMAN,Q13571;LAPM5_HUMAN,Q96JM2;ZN462_HUMAN,P35558;PCKGC_HUMAN
model_id,,,,,,,,,,,,,,,,,,,,,
SIDM00018,7.10955,3.41494,0.00000,7.86661,3.89547,4.19666,0.0,0.00000,3.19088,7.35806,...,0.0,0.0,3.90064,2.63998,0.0,0.0,0.0,0.0,0.0,0.0
SIDM00023,6.82802,4.14346,2.23781,7.62878,3.19811,4.60902,0.0,2.47059,3.69535,5.70790,...,0.0,0.0,0.00000,3.19608,0.0,0.0,0.0,0.0,0.0,0.0
SIDM00040,7.01426,4.19987,2.44055,8.12459,0.00000,4.76881,0.0,0.00000,0.00000,5.52283,...,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0
SIDM00041,5.28591,3.35789,0.00000,7.97268,0.00000,4.52092,0.0,0.00000,2.73088,4.29429,...,0.0,0.0,0.00000,2.79023,0.0,0.0,0.0,0.0,0.0,0.0
SIDM00042,5.70786,0.00000,0.00000,6.22574,0.00000,4.49579,0.0,0.00000,2.87981,0.00000,...,0.0,0.0,0.00000,0.00000,0.0,0.0,0.0,0.0,0.0,0.0